### ISSUE TITLE
Synchronize with ECCC's GitLab instance

### ISSUE THREAD

**Issue by DanielMichelson** [wmo-ipet-owr/rb52odim#4]
This project originated on an internal GitLab server in Canada. At this point, it no longer makes sense to have separate projects, so this one on GitHub should take over.<br>
To do so, this project needs to be synchronized with the one in Canada.

**Comment by wmo-ipet-owr** [comment]
Resolved in version 1.1, which also seems to be tagged v1.0.2-2-g3c58370
