### ISSUE TITLE
isRainbow5 check crashes

### ISSUE THREAD

**Issue by wmo-ipet-owr** [wmo-ipet-owr/rb52odim#5]
isRainbow5 crashes (segfault) on gzipped RB5 files. 
It should instead return RETURN_no or False in Python.

**Comment by Peter-Rodriguez** [comment]
Forked by Peter-Rodriguez@github.com... Pull request forthcoming.
Add isRainbow5buf() check for proper read header line... Looking for EOL, pointer may return NULL.
Add unittest for isRainbow5(gzip_file).

**Comment by wmo-ipet-owr** [comment]
Fixed with PR #6
